services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "54545:54545"
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:54545/api/v1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge